# Generated by Django 4.2 on 2023-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nat_id',
            field=models.IntegerField(default=0),
        ),
    ]
